spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: AuthenticationFilter
        - id: income-expense"
          uri: lb://INCOME-EXPENSE
          predicates:
            - Path=/api/v1/currency/**
          filters:
            - name: AuthenticationFilter